version: "3"
services:
    db:
        image: mongo:latest
        restart: always
        container_name: db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "9000:27017"
        networks:
            - assignment-network
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "9001:9001"
        restart: always
        volumes:
            - "./:/app"
        depends_on:
            - db
        networks:
            - assignment-network

networks:
    assignment-network:
        driver: bridge
